import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
const browser=await chromium.launch();
const page=await browser.newPage();
await page.goto('http://127.0.0.1:5173/?form=4&subject=Chemistry');
assert.equal(await page.locator('.simulation').count(),4);
assert.equal(await page.locator('#view-title').textContent(),'Form 4 Chemistry');
assert.equal(await page.locator('.form-art svg').count(),10);
await page.locator('#subject').selectOption('Physics');
assert.ok(page.url().includes('subject=Physics'));
await page.goBack();
assert.equal(await page.locator('.simulation').count(),4);
await page.reload();
assert.equal(await page.locator('.simulation').count(),4);
await page.locator('#reset').click();
assert.equal(await page.locator('.simulation').count(),56);
await page.goto('http://127.0.0.1:5173/');
await page.keyboard.press('Tab');
assert.equal(await page.evaluate(()=>document.activeElement.className),'skip-link');
await page.keyboard.press('Enter');
assert.equal(await page.evaluate(()=>document.activeElement.id),'main');
await page.emulateMedia({reducedMotion:'reduce'});
assert.equal(await page.locator('.form-card').first().evaluate(el=>getComputedStyle(el).transitionDuration),'0s');
await page.setViewportSize({width:320,height:640});
assert.equal(await page.locator('header').count(),0);
assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
const image=await page.request.get('http://127.0.0.1:5173/classroom-v2.jpg');assert.ok(image.ok());
await browser.close();
console.log('Shareable filters, reload, history, All Simulations reset, keyboard skip link, reduced motion, touch targets and classroom asset: PASS');
